root: true
extends: ['eslint:recommended']
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', 'typescript', 'import']
rules:
  semi: ['error', 'always']
  max-lines-per-function: ['warn', 60]
  eqeqeq: 'error'
  max-lines: ['warn', 300]
  no-console: ['error', { 'allow': ['warn', 'error'] }]
  no-var: 'error'
  quotes: ['error', 'single']
env:
  browser: true
