semi: true
singleQuote: true
printWidth: 80 # Useful when viewing multiple files side-by-side
tabWidth: 2
arrowParens: 'always' # useful for TypeScript and recommended by Prettier
trailingComma: 'all' # consistency, consistency, consistency
